# See: https://github.com/wengchaoxi/docker-library

name: Build and push `docsgpt` docker image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - docsgpt/*
      - .github/workflows/docsgpt.yml
  pull_request:
    branches:
      - main
    paths:
      - docsgpt/*

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: [application, frontend]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up qemu
        uses: docker/setup-qemu-action@v2

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          file: docsgpt/${{ matrix.app }}/Dockerfile
          platforms: linux/amd64
          context: docsgpt/${{ matrix.app }}
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/docsgpt-${{ matrix.app }}:latest
