# See: https://github.com/wengchaoxi/docker-library

name: Build and push `sd-webui` docker image

env:
  IMAGE_TAG: "1.6.0"
  SD_WEBUI_SHA: "5ef669de080814067961f28357256e8fe27544f4"
  SD_WEBUI_CONTROLNET_SHA: "2ecec1327481cc83d562fb705b0e14b3875d2c7e"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - sd-webui/*
      - .github/workflows/sd-webui.yml
  pull_request:
    branches:
      - main
    paths:
      - sd-webui/*

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up qemu
        uses: docker/setup-qemu-action@v2

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          file: sd-webui/Dockerfile
          platforms: linux/amd64
          context: sd-webui
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/sd-webui:${{ env.IMAGE_TAG }}
            ${{ secrets.DOCKER_USERNAME }}/sd-webui:latest
          build-args: |
            SD_WEBUI_SHA=${{ env.SD_WEBUI_SHA }}
            SD_WEBUI_CONTROLNET_SHA=${{ env.SD_WEBUI_CONTROLNET_SHA }}
