name: 'Submodules Update'

on:
  schedule:
  # https://cron.help/#0_2_*_*_*
  - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  submodules-update:
    name: 'Submodules Update'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Update submodules
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive

      - name: Commit changes
        run: |
          git config user.name 'bot'
          git config user.email 'bot@noreply.github.com'
          git remote set-url origin https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}
          git commit -am "Auto update submodules" && git push || echo "No changes to commit"
